package com.bakuard.nutritionManager.validation;

public enum Constraint {

    NOT_NULL,
    MUST_BE_NULL,
    NOT_BLANK,
    NOT_CONTAINS_BLANK,
    STRING_LENGTH,
    NOT_NEGATIVE_VALUE,
    POSITIVE_VALUE,
    NOT_CONTAINS_NULL,
    NOT_CONTAINS_NEGATIVE,
    NOT_CONTAINS_DUPLICATE,
    NOT_CONTAINS_ITEM,
    CONTAINS_AT_LEAST,
    CONTAINS_THE_SAME_ITEMS,
    RANGE,
    EQUAL,
    CORRECT_URL,
    DOES_NOT_THROW,
    ENTITY_MUST_UNIQUE_IN_DB,
    ENTITY_MUST_EXISTS_IN_DB,
    CORRECT_JWS,
    PERMISSIBLE_VALUE

}
