name: deploy
run-name: ${{ github.actor }} deploy NutritionManager on AWS

on: 
    push: 
        branches: 
            - 'cicd'
    pull_request: 
        branches: 
            - 'cicd'

jobs: 
    run-unit-tests: 
        runs-on: ubuntu-latest
        steps: 
            - name: copy my repository to runner
              uses: actions/checkout@v3
            - name: Set up JDK 17
              uses: actions/setup-java@v3
              with: 
                  java-version: '17'
                  distribution: adopt-hotspot
            - name: Set up Postgresql
              run: |
                  sudo apt update
                  sudo apt install postgresql postgresql-contrib
                  sudo systemctl start postgresql.service
            - name: create database and user
              run: |
                  psql
                  create database "NutritionManagerUnitTest";
                  create user nutrition_manager_tester with encrypted password 'nutrition_manager_tester';
                  grant all privileges on database "NutritionManagerUnitTest" to nutrition_manager_tester;
                  \q
